name: Release Advanced Close All Extension

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.1.0, etc.

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Compile and build
      run: npm run package
      
    - name: Install vsce
      run: npm install -g @vscode/vsce
      
    - name: Package extension
      run: vsce package
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: Advanced Close All v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Advanced Close All v${{ steps.get_version.outputs.VERSION }}
          
          ### 🚀 Features
          - Intelligent tab closing with multiple modes
          - Support for all tab types (editors, extension details, settings pages)
          - Configurable status bar button and custom keybindings  
          - Cross-platform support (Windows/Linux/macOS)
          
          ### 📦 Installation
          1. Download the `.vsix` file from this release
          2. Open VS Code
          3. Press `Ctrl+Shift+P` (or `Cmd+Shift+P` on macOS)
          4. Type "Extensions: Install from VSIX..."
          5. Select the downloaded `.vsix` file
          
          ### 🔗 VS Code Marketplace
          Also available on the [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=addozhang.advanced-close-all)
          
          ### 📄 Documentation
          See the [README](https://github.com/addozhang/vscode-close-all-extension/blob/main/README.md) for detailed usage instructions.
        files: |
          ./advanced-close-all-${{ steps.get_version.outputs.VERSION }}.vsix
        draft: false
        prerelease: false

        
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: advanced-close-all-${{ steps.get_version.outputs.VERSION }}
        path: ./advanced-close-all-${{ steps.get_version.outputs.VERSION }}.vsix
        retention-days: 90

  # Optional: Auto-publish to VS Code Marketplace
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'addozhang/vscode-close-all-extension' && startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Compile and build
      run: npm run package
      
    - name: Install vsce
      run: npm install -g @vscode/vsce
      
    - name: Publish to VS Code Marketplace
      run: vsce publish --pat ${{ secrets.VSCE_TOKEN }}
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}